import {
  Personal,
  Corporate,
  Business,
  Custom,
  Dashboard,
  Transactions,
  Accounts,
  Investment,
  Credit,
  Loans,
  Service,
  Privileges,
  Setting,
} from "../src/assets/Icon";

export const CONSTANT = {
  LOAN_HEADING: "Active Loans Overview",
  LOAN_DATA: [
    {
      srNo: "01.",
      loanMoney: "$100,000",
      leftToPay: "$40,500",
      duration: "8 months",
      interestRate: "12%",
      installment: "$2,000/month",
    },
    {
      srNo: "02.",
      loanMoney: "$500,000",
      leftToPay: "$250,000",
      duration: "36 months",
      interestRate: "10%",
      installment: "$8,000/month",
    },
    {
      srNo: "03.",
      loanMoney: "$900,000",
      leftToPay: "$40,500",
      duration: "12 months",
      interestRate: "12%",
      installment: "$5,000/month",
    },
    {
      srNo: "04.",
      loanMoney: "$50,000",
      leftToPay: "$40,500",
      duration: "25 months",
      interestRate: "5%",
      installment: "$2,000/month",
    },
    {
      srNo: "05.",
      loanMoney: "$50,000",
      leftToPay: "$40,500",
      duration: "5 months",
      interestRate: "16%",
      installment: "$10,000/month",
    },
    {
      srNo: "06.",
      loanMoney: "$80,000",
      leftToPay: "$25,500",
      duration: "14 months",
      interestRate: "8%",
      installment: "$2,000/month",
    },
    {
      srNo: "07.",
      loanMoney: "$12,000",
      leftToPay: "$5,500",
      duration: "9 months",
      interestRate: "13%",
      installment: "$500/month",
    },
    {
      srNo: "08.",
      loanMoney: "$160,000",
      leftToPay: "$100,800",
      duration: "3 months",
      interestRate: "12%",
      installment: "$900/month",
    },
  ],
  LOAN_TAG_DATA: [
    {
      type: "Personal",
      amount: "$50,000",
      icon: Personal(),
      bgColor: "#E7EDFF",
    },
    {
      type: "Corporate",
      amount: "$100,000",
      icon: Corporate(),
      bgColor: "#FFF5D9",
    },
    {
      type: "Business",
      amount: "$500,000",
      icon: Business(),
      bgColor: "#FFE0EB",
    },
    {
      type: "Custom",
      amount: "Choose money",
      icon: Custom(),
      bgColor: "#DCFAF8",
    },
  ],
  TABLE_HEADER: [
    "SL No",
    "Loan Money",
    "Left To Pay",
    "Duration",
    "Interest Rate",
    "Installment",
    "Repay",
  ],
  REPAY_BTN_TEXT: "Repay",
  SIDEBAR_OPTIONS: [
    { text: "Dashboard", icon: Dashboard(), key: "Dashboard" },
    { text: "Transactions", icon: Transactions(), key: "Transactions" },
    { text: "Accounts", icon: Accounts(), key: "Accounts" },
    { text: "Investments", icon: Investment(), key: "Investment" },
    { text: "Credit Cards", icon: Credit(), key: "Credit" },
    { text: "Loans", icon: Loans(), key: "Loans" },
    { text: "Services", icon: Service(), key: "Service" },
    { text: "My Privileges", icon: Privileges(), key: "Privileges" },
    { text: "Setting", icon: Setting(), key: "Setting" },
  ],
  DASHBOARD_CONTENT: "This is Dashboard Section",
  TRANSACTIONS_CONTENT: "This is Transactions Section",
  ACCOUNTS_CONTENT: "This is Accounts Section",
  INVESTMENT_CONTENT: "This is Investment Section",
  CREDIT_CONTENT: "This is Credit Section",
  SERVICE_CONTENT: "This is Service Section",
  PRIVILIGES_CONTENT: "This is Privileges Section",
  SETTING_CONTENT: "This is Setting Section",
};
